name: NES to NSF Converter

on:
  push:
    paths:
      - 'roms/**.nes' # 'roms'ディレクトリ内の.nesファイルがpushされたときに実行

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and Extract nes2nsf
      run: |
        # NSFPlayの最新版をダウンロードして展開します
        wget http://nsfplay.com/download/nsfplay24-src.zip -O nsfplay.zip
        unzip nsfplay.zip
        # nes2nsfツールをビルドします
        g++ -o nes2nsf nsfplay/misc/nes2nsf.cpp

    - name: Convert .nes to .nsf
      run: |
        # 'roms'ディレクトリ内のすべての.nesファイルを探して変換します
        find roms -name "*.nes" | while read nesfile; do
          nsffile="${nesfile%.nes}.nsf"
          ./nes2nsf "$nesfile" "$nsffile"
          echo "Converted $nesfile to $nsffile"
        done

    - name: Commit and Push .nsf files
      run: |
        # Gitのユーザー情報を設定します
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        # 生成された.nsfファイルを追加してコミットします
        git add roms/*.nsf
        # 変更がある場合のみコミットとプッシュを実行します
        if ! git diff --cached --quiet; then
          git commit -m "Automated conversion of .nes to .nsf"
          git push
        else
          echo "No changes to commit."
        fi
